/**
 * Catalog of AI image watermark / provenance signals.
 *
 * Layers:
 * 1. Byte / C2PA Soft Binding — open Content Credentials declarations,
 *    including Google DeepMind SynthID (used by Gemini/Imagen and, since
 *    May 2026, OpenAI ChatGPT / GPT image / API) via Soft Binding and the
 *    signed `c2pa.watermarked.unbound` action.
 * 2. Visible burned-in marks (Grok corner logo, “AI generated”, …).
 * 3. Pixel SynthID surrogate (OpenSynthID) — separate module; Google’s
 *    official detector is proprietary and not redistributable.
 */

/** Generator / product names commonly embedded in Software, XMP, C2PA. */
export const AI_SOFTWARE_PATTERNS: readonly RegExp[] = [
  /\bmidjourney\b/i,
  /\bstable[\s_-]?diffusion\b/i,
  /\bstability[\s_-]?ai\b/i,
  /\bdall[\s.·-]?e\b/i,
  /\bchatgpt\b/i,
  /\bopenai\b/i,
  /\bgpt[\s_-]?image\b/i,
  /\bsora\b/i,
  /\badobe\s*firefly\b/i,
  /\bfirefly\b/i,
  /\bcontentcredentials\b/i,
  /\bflux(\.1|[_\s-]?dev|[_\s-]?pro|[_\s-]?schnell)?\b/i,
  /\bblack[\s_-]?forest[\s_-]?labs\b/i,
  /\bcomfyui\b/i,
  /\bautomatic1111\b/i,
  /\ba1111\b/i,
  /\binvokeai\b/i,
  /\bnightcafe\b/i,
  /\bleonardo\.?ai\b/i,
  /\bideogram\b/i,
  /\bgrok\b/i,
  /\bxai\b/i,
  /\bgrok[\s_-]?imagine\b/i,
  /\bgemini\b/i,
  /\bimagen\b/i,
  /\bimagefx\b/i,
  /\bvertexai\b/i,
  /\bdeepmind\b/i,
  /\bsynthid\b/i,
  /\breve\b/i,
  /\bcivitai\b/i,
  /\brecraft\b/i,
  /\brunway\b/i,
  /\bluma[\s_-]?ai\b/i,
  /\bdreamstudio\b/i,
  /\bcraiyon\b/i,
  /\bwombo\b/i,
  /\bstarryai\b/i,
  /\bclipdrop\b/i,
  /\bphotoleap\b/i,
  /\bcanva\b/i,
  /\bmagic[\s_-]?studio\b/i,
  /\bcopilot\b/i,
  /\bbing[\s_-]?image[\s_-]?creator\b/i,
  /\bmicrosoft[\s_-]?designer\b/i,
  /\bdesigner\.microsoft\b/i,
  /\bpicas\b/i,
  /\bperchance\b/i,
  /\bnovelai\b/i,
  /\bwaifu[\s_-]?diffusion\b/i,
  /\byandexart\b/i,
  /\bkandinsky\b/i,
  /\bfusion[\s_-]?brain\b/i,
  /\balibaba\b/i,
  /\btongyi\b/i,
  /\bqwen[\s_-]?vl\b/i,
  /\bbai[\s_-]?du\b/i,
  /\bernie\b/i,
  /\bwenxin\b/i,
  /\bhuggingface\b/i,
  /\bdiffusers\b/i,
  /\bmagnific(?!ent)\b/i,
  /\blucidpic\b/i,
  /\bimagineme\b/i,
  /\blogoai\b/i,
  /\bgenerated\.photos\b/i,
  /\bthispersondoesnotexist\b/i,
  /\bartbreeder\b/i,
  /\bpromptbase\b/i,
  /\blexica\b/i,
  /\bcraiyon\b/i,
  /\bai[\s_-]?generated\b/i,
  /\bgenerated\s+with\s+ai\b/i,
  /\bcreated\s+with\s+ai\b/i,
  /\bmade\s+with\s+ai\b/i,
  /\bgenerated\s+by\s+ai\b/i,
  /\bartificial\s+intelligence\b/i,
  /\btrainedalgorithmicmedia\b/i,
  /\bcompositedwithtrainedalgorithmicmedia\b/i,
  /\balgorithmic[\s_-]?media\b/i,
];

/**
 * SynthID / Soft Binding / Content Credentials — Google’s invisible watermark
 * standard as declared in C2PA (OpenAI embeds these alongside SynthID).
 * Matched before generic generator names so detail strings stay specific.
 */
export const SYNTHID_SOFT_BINDING_PATTERNS: readonly RegExp[] = [
  /c2pa\.watermarked\.unbound/i,
  /c2pa\.watermarked/i,
  /c2pa\.softbinding/i,
  /soft[\s_-]?binding/i,
  /\bsynthid\b/i,
  /deepmind\.google\/.*synthid/i,
  /ai\.google\.dev\/.*synthid/i,
  /watermarked\.unbound/i,
  /"action"\s*:\s*"c2pa\.watermarked/i,
  /softBinding(s|Algorithms?)?/i,
  /watermark\.softbinding/i,
  /com\.google\.synthid/i,
  /org\.c2pa\.softbinding/i,
];

/** Parameter blocks, C2PA actions, Soft Binding, regional AIGC labels. */
export const AI_PARAM_PATTERNS: readonly RegExp[] = [
  ...SYNTHID_SOFT_BINDING_PATTERNS,
  /\bsampler\s*[:=]/i,
  /\bcfg\s*scale\s*[:=]/i,
  /\bsteps\s*[:=]\s*\d+/i,
  /\bnegative\s*prompt\s*[:=]/i,
  /\btxt2img\b/i,
  /\bimg2img\b/i,
  /\binpaint(ing)?\b/i,
  /\bmodel\s*hash\s*[:=]/i,
  /\bclip\s*skip\s*[:=]/i,
  /\bvae\s*[:=]/i,
  /\blora\b/i,
  /\bcontrolnet\b/i,
  /digitalSourceType/i,
  /c2pa\.actions(\.v2)?/i,
  /\bc2pa\b/i,
  /\bjumb(f)?\b/i,
  /claim_generator/i,
  /claimGenerator/i,
  /http:\/\/cv\.iptc\.org\/newscodes\/digitalsourcetype\//i,
  /trainedAlgorithmicMedia/i,
  /compositeWithTrainedAlgorithmicMedia/i,
  /algorithmicEnhancement/i,
  // PNG tEXt/zTXt/iTXt key used by China AIGC labeling (and similar embeds).
  /ptEXtAIGC/i,
  /AIGCLabel/i,
  /ContentProducer/i,
  /ProduceID/i,
  /ReservedCode1/i,
  /ai_generated/i,
  /"Label"\s*:\s*"1"/,
  /dcterms:provenance/i,
  /xmpMM:History/i,
  /instanceID.*firefly/i,
  /cai:Assertion(s)?/i,
  /contentcredentials/i,
  /contentauthenticity/i,
];

/**
 * Visible burned-in watermark phrases (normalized lowercase, no spaces for
 * matching). Matched against OCR-lite corner scans.
 */
export const VISIBLE_WATERMARK_PHRASES: readonly string[] = [
  "grok",
  "xai",
  "chatgpt",
  "openai",
  "dalle",
  "dall·e",
  "dall-e",
  "midjourney",
  "firefly",
  "adobefirefly",
  "ideogram",
  "gemini",
  "imagen",
  "imagefx",
  "copilot",
  "designer",
  "leonardo",
  "leonardoai",
  "nightcafe",
  "craiyon",
  "bing",
  "recraft",
  "runway",
  "runwayml",
  "luma",
  "lumalabs",
  "flux",
  "stablediffusion",
  "stabilityai",
  "dreamstudio",
  "wombo",
  "starryai",
  "clipdrop",
  "canva",
  "novelai",
  "perchance",
  "synthesia",
  "aigenerated",
  "generatedwithai",
  "createdwithai",
  "madewithai",
  "generatedbyai",
  "madewithmidjourney",
  "createdwithchatgpt",
  "generatedbygrok",
];
